### ISSUE TITLE
Language models are not downloaded from 'downloadModel' in google_mlkit_translation

### ISSUE THREAD

**Issue by Waruna-Kaushalya** [flutter-ml/google_ml_kit_flutter#312]
Language models are not downloaded from downloadModel in google_mlkit_translation. But when translating by translateText, if the relevant language model is not downloaded, the model will be downloaded automatically. And it is translated correctly. What is the reason for this? (deleteModel also works).

DEBUG CONSOLE
```dart
D/TransportRuntime.SQLiteEventStore( 6258): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 6258): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
```

Tested
isWifiRequired: true & isWifiRequired: false
```dart
final returnString = await modelManager
        .downloadModel(TranslateLanguage.hindi.bcpCode, isWifiRequired: true)
        .then((value) => value ? 'done' : 'error');
```

minSdkVersion 26
compileSdkVersion 31
targetSdkVersion 31
Flutter 3.0.5

Tested with: 
Samsung A105F(android-arm)
Samsung SM N9600(android-arm64)

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=-4o0YV-2vic

**Comment by fbernaly** [comment]
There are 2 approaches here:
1) you can download the models previous to calling translate using `OnDeviceTranslatorModelManager` which has methods to `downloadModel()`, `deleteModel()`, and check if a model is downloaded `isModelDownloaded()`.
2) you can let the translator to download the models for you. In this approach the initial translation it will take more time because it is downloading the models, but subsequent translations will be faster.

I doubled checked our example app and the API is working as I described. I updated the example app (https://github.com/flutter-ml/google_ml_kit_flutter/pull/474) to allow the user select different languages. If you download the models first you will see that the translations it is immediately. If you select new languages without downloading the models and try to translate then it will take longer because it is downloading the models. But the second time it will be faster.

According to the documentation that behavior is correct:
* Approach 1: [Explicitly manage translation models](https://developers.google.com/ml-kit/language/translation/android#manage-models).
* Approach 2:  Let the translator to download the model for you: in step 2 in section [Translate a string of text](https://developers.google.com/ml-kit/language/translation/android#translate-text).
