### ISSUE TITLE
I can't use custom model from teachable machine

### ISSUE THREAD

**Issue by argyaa** [flutter-ml/google_ml_kit_flutter#410]
Sorry I am beginner here, I'm learning to use custom model from [teachable machine](https://teachablemachine.withgoogle.com) because I can't make my own model but when I use it in my app it throws an error. I just replaced the default model in assets to my own model. is there a tutorial I should learn?

**Comment by Pinteezy** [comment]
yeah me too I found that for some reason when I exported as quantized model it made the error go away. But I find that it doesn't accept the labels file from teachable machine. So I run this model and it just returns a bunch of empty labels and I am assuming because I can't provide it the labels.txt file teachable machine generates

**Comment by fbernaly** [comment]
From Google's documentation: https://developers.google.com/ml-kit/custom-models
