### ISSUE TITLE
google_mlkit_translation: change letters case after translate

### ISSUE THREAD

**Issue by prasant10050** [flutter-ml/google_ml_kit_flutter#468]
why this plugin change letters case after translate. It effects the application's behavior and durability in my production code. I have two languages in my app - English and Arabic. When I translate from Arabic to english then my all words are starting with uppercase letter instead of that sentence case or original case. Given sample below
Original : Text in english - 'Enter the full name' , Result in Arabic is - 'أدخل الاسم الكامل' and it is fine, but when i'm doing the reverse translation from Arabic text to english it is showing 'Enter The Full Name".

**Comment by fbernaly** [comment]
That is a question for Google.

Please read the first section on our [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_translation) where we explain how the FlutterMethodChannels for this plugin work.

Since this plugin is a wrapper around Google's native APIs, I recommend you post this issue in their repo. Try their native app to double check that that behavior for the translations comes from their native API.
