### ISSUE TITLE
[Text Recognition] TextRecognizer fails detect if a given TextRecognitionScript isn't ready

### ISSUE THREAD

**Issue by njovy** [flutter-ml/google_ml_kit_flutter#631]
There's no way to check if TextRecognizer has a given TextRecognitionScript. It would be great if we could check before processing an image, rather than relying on exceptions.

Is there a way to remove a downloaded TextRecognitionScript?

**Comment by fbernaly** [comment]
https://github.com/flutter-ml/google_ml_kit_flutter/blob/develop/packages/google_mlkit_commons/lib/src/model_manager.dart#L39-L45

**Comment by njovy** [comment]
@fbernaly Thank you for a rapid response. OnDeviceTranslator or some other packages have a method to check if model is downloaded. I don't see that code in [TextRecognizer.java](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_text_recognition/android/src/main/java/com/google_mlkit_text_recognition/TextRecognizer.java).

**Comment by njovy** [comment]
@fbernaly Thank you for the rapid response. OnDeviceTranslator or some other packages have a method to check if the translation model is downloaded. I don't see that code in [TextRecognizer.java](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_text_recognition/android/src/main/java/com/google_mlkit_text_recognition/TextRecognizer.java), how do I use ModelManager to manage language models? The translation plugin doesn't fail to translate. It starts to download, then translates. However, I don't see that behavior in text recognition.

**Comment by fbernaly** [comment]
[TextRecognition](https://github.com/flutter-ml/google_ml_kit_flutter/tree/develop/packages/google_mlkit_text_recognition) does not require model managing, because model is already included in the API.
[On Device Translation](https://github.com/flutter-ml/google_ml_kit_flutter/tree/develop/packages/google_mlkit_translation#managing-remote-models) does require model managing.
- https://github.com/flutter-ml/google_ml_kit_flutter/tree/develop/packages/google_mlkit_translation#managing-remote-models
- https://github.com/flutter-ml/google_ml_kit_flutter/blob/develop/packages/google_mlkit_commons/lib/src/model_manager.dart
