### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by Ranbir-nexever** [flutter-ml/google_ml_kit_flutter#691]
### Describe your issue. If applicable, add screenshots to help explain your problem.

backtrace:
      #00 pc 0000000000035528  /apex/com.android.art/lib64/libjavacore.so (Memory_peekByte(_JNIEnv*, _jclass*, long)+0) (BuildId: 8d85311607fdef69ea901998b2a938b1)
      #01 pc 00000000020f40e4  /memfd:jit-cache (deleted)

### Steps to reproduce.

open camera screen many times

### What is the expected result?

app is crashed

### Did you try our example app?

No

### Is it reproducible in the example app?

Yes

### Reproducible in which OS?

Android

### Flutter/Dart Version?

3.22.2

### Plugin Version?

google_mlkit_text_recognition: ^0.11.0

**Comment by bensonarafat** [comment]
Could you try the example app?

**Comment by Ranbir-nexever** [comment]
I tried  but latest camera latest version image format give yuv_420_888
 but code is run with  nv21  so its not recognised text
thanktyou

**Comment by bensonarafat** [comment]
Okay, I have to close this. Look at this issue #684

**Comment by pvlKryu** [comment]
**Working Configuration:**

```
  google_mlkit_face_detection: 0.11.0
  camera: 0.11.0+2
  camera_android_camerax: 0.6.7+2
```
  
**Problem:**
The issue arises when using `google_mlkit_face_detection: ^0.11.0` or `google_mlkit_face_detection: 0.12.0` without explicitly specifying the version `camera_android_camerax: 0.6.7+2`. This happens because `camera: 0.11.0+2` uses `camera_android_camerax: 0.6.8+2 `under the hood, which causes build errors.

**Solution:**
By explicitly setting `camera_android_camerax: 0.6.7+2` and `google_mlkit_face_detection: 0.11.0`. Using this config it is still the new `camera_android_camerax` under the hood in the `camera` package.
